<CameraPanel>
    orientation: "vertical"
    camera: camera
    image: image
    Camera:
        id: camera
        resolution: (320, 240)
        play: True
    Image:
        id: image
    ToggleButton:
        text: "Play"
        height: "48dp"
        size_hint_y: None
        on_press: camera.play = not camera.play
    Button:
        text: "Capture"
        height: "48dp"
        size_hint_y: None
        on_press: root._capture()